config/routes.rb
Rails.application.routes.draw do
  resources :users do
   member do
      get 'activate'
     put 'activate'
   end
  end

  resources :sintomadoencas, shallow: true do
    resources :doencas
  end

get "users/:id/activate" => "users#activate", :as => "active_user"
  
  get 'doencas/new'

  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get 'signup'  => 'users#new'
  get 'm_signup'=> 'users#new_m'
  get 'edit'    => 'users#edit'
  #post 'users/ativar_medico'
  
  
  
  get 'add'     => 'doencas#new'
  get 'index_d' => 'doencas#index'
  get 'edit'    => 'doencas#edit'
  
  get 'add_sintoma' => 'sintomas#new'
  get 's_index' => 'sintomas#index'
  #get 'busca' => 'sintomas#search'
  get 'edit' => 'sintomas#edit'
  
  resources :account_activations, only: [:edit]

  resources :users
  
  resources :doencas 
  resources :sintomas
  resources :sintomadoencas
  
  get 'sd' => 'sintomadoencas#new' 
  get 'search' => 'sintomadoencas#search'
  get 'remove' => 'sintomadoencas#delete'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Sobre") %>
<h1>Sobre</h1>
<p>
  Panacea - Plataforma de diagnóstico individual e base de informações médicas. </p>

<p> Esse site não deve ser tratado como mais do que um objeto de pesquisa 
  e referência e não tem o objetivo de substituir uma opinião médica embasada. </p>

<p>Essa ferramenta deve ser usada para se estimar as possíveis condições médicas 
  do usuário para facilitar a escolha de um profissional ou adquirir informações
  sobre profissionais nas proximidades do usuário.</p>

<p>Esse site não incentiva a auto-medicação.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contato') %>
<h1>Contato</h1>
<p> Bruno da Costa Damaceno </p>
<p> Contato: damacenob@hotmail.com</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  <h2>
      <p></p>
  </h2>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <%= image_tag("Panacea_LVT.png", :alt => "Logo Panacea") %>

  <h2>
    Plataforma de diagnóstico inicial e base de conhecimento médico. <br />
    Usuários registrados tem acesso à pesquisa de doenças a partir de sintomas.<br />
    Além disso, médicos registrados podem adicionar ao banco de dados e sugerir mudanças 
  pertinentes a doenças já registradas. <br />     <br />

  <% unless logged_in? %>
    <%= link_to "Crie sua conta", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Médico? Crie sua conta aqui.", m_signup_path, class: "btn btn-lg btn-danger" %> <br />
    Já possui uma conta? <%= link_to "Clique aqui", login_path %>
  <% end %>
  <% if logged_in? %>
    <%= link_to "Busca de doenças", s_index_path, class: "btn btn-lg btn-primary" %>
  <% end %>
  
  </h2>
</div>