config/routes.rb
Rails.application.routes.draw do
  resources :users do
   member do
      get 'activate'
     put 'activate'
   end
  end

  resources :sintomadoencas, shallow: true do
    resources :doencas
  end

get "users/:id/activate" => "users#activate", :as => "active_user"
  
  get 'doencas/new'

  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get 'signup'  => 'users#new'
  get 'm_signup'=> 'users#new_m'
  get 'edit'    => 'users#edit'
  #post 'users/ativar_medico'
  
  
  
  get 'add'     => 'doencas#new'
  get 'index_d' => 'doencas#index'
  get 'edit'    => 'doencas#edit'
  
  get 'add_sintoma' => 'sintomas#new'
  get 's_index' => 'sintomas#index'
  #get 'busca' => 'sintomas#search'
  get 'edit' => 'sintomas#edit'
  
  resources :account_activations, only: [:edit]

  resources :users
  
  resources :doencas 
  resources :sintomas
  resources :sintomadoencas
  
  get 'sd' => 'sintomadoencas#new' 
  get 'search' => 'sintomadoencas#search'
  get 'remove' => 'sintomadoencas#delete'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token
  before_create :create_activation_digest
  before_save { self.email = email.downcase }
  validates :nome,  presence: true, length: { maximum: 50 }
  validates :telefone, presence: true, length: {maximum: 15}
  validates :endereco, presence: true, length: {maximum: 100}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :historicos
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
  end
  
  def activate_user 
  self.activated = 'true'
  self.save
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def activate
    self.update_attribute!(:active, true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
    @users = User.find_by_especializacao(params[:especializacao])
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @historicos = Historico.find_by_user_id(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def new_m
    @user = User.new
  end
  
  def activate
  @user = User.find(params[:id])
  if @user.update_attribute(:activated, true)
    redirect_to root_url
  else
    flash[:danger] = "Houve um erro com a validação do usuário"
   render root_url
  end 
  end
  
  def ativar_medico
    @user = User.find(params[:id])
    @user.activated = true
    if @user.save 
      flash[:info] = "Usuário registrado como médico"
     # render 'show'
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      #@user.login
      @user.send_activation_email
      flash[:info] = "Bem-vindo a Panacea!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
     flash[:success] = "Perfil atualizado."
     redirect_to @user
    else
      render 'edit'
    end
  end
  
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Você precisa estar conectado."
        redirect_to login_url
      end
    end
    
    
  
  private

    def user_params
      params.require(:user).permit(:nome, :email, :endereco, :telefone, :password,
                                   :password_confirmation, :tipo, :crm, :especializacao, :activated)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) || current_user.tipo == "A"
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.nome, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.nome, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Altere suas Informações') %>
<h1>Edite seu perfil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :nome %>
      <%= f.text_field :nome, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :endereco, "Endereço" %>
      <%= f.text_field :endereco, class: 'form-control' %>

      <%= f.label :telefone, "Telefone" %>
      <%= f.text_field :telefone, class: 'form-control' %>

      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, :value => @user.password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirme sua senha" %>
      <%= f.password_field :password_confirmation, :value => @user.password, class: 'form-control' %>
      
      <% if @user.tipo == "A" %>
        <%= f.label :tipo, "Tipo de Usuário" %>
        <%= f.select :tipo, options_for_select([['Admin', 'A'], ['Usuario', 'U'], ['Médico', 'M']]) %> 
      <% end %>
      <%= f.submit "Salvar alterações", class: "btn btn-primary" %>
    <% end %>
    
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Mudar</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Usuarios') %>
<h1>Todos os usuários</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

</ul>

app/views/users/new.html.erb
<% provide(:title, 'Registro') %>
<h1>Inscreva-se</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages' %>

      <%= f.label :nome %>
      <%= f.text_field :nome, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :endereco, "Endereço" %>
      <%= f.text_field :endereco, class: 'form-control' %>

      <%= f.label :telefone, "Telefone" %>
      <%= f.text_field :telefone, class: 'form-control' %>
      
      <%= f.hidden_field :tipo, :value => "U" %>
      <%= f.hidden_field :activated, :value => false %>
      <%= f.hidden_field :crm, :value => "0" %>
      <%= f.hidden_field :especializacao, :value => "0" %>


      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirme sua senha" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crie sua conta", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/users/new_m.html.erb
<% provide(:title, 'Registro') %>
<h1>Inscreva-se</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages' %>

      <%= f.label :nome %>
      <%= f.text_field :nome, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :endereco, "Endereço" %>
      <%= f.text_field :endereco, class: 'form-control' %>

      <%= f.label :telefone, "Telefone" %>
      <%= f.text_field :telefone, class: 'form-control' %>
      
      <%= f.label :especializazao, "Especialização:" %>
      <%= f.text_field :especializacao, class: 'form-control' %>
      
      <%= f.label :crm, "Código CRM:" %>
      <%= f.text_field :crm, class: 'form-control' %>
      
      <%= f.hidden_field :tipo, :value => "M" %>
      <%= f.hidden_field :activated, :value => false %>
      
      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirme sua senha" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crie sua conta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.nome) %>
<div class="row">
 <!-- <aside class="col-md-4"> -->
    
      <h1>
        <%= gravatar_for @user %> 
        <% if @user.tipo == "M" %>
          Dr(a).
        <% end %>
        <%= @user.nome %> 
      </h1>
        
        
      <% if current_user == @user %>
        <aside class="col-md-4">
          <% if @user.tipo == "M" || @user.tipo == "A" %>
            <% if @user.activated == true %>
              <%= link_to "Adicionar doenças ", add_path, class: "btn btn-lg btn-primary" %>
              <br />
              <%= link_to "Adicionar sintomas", add_sintoma_path, class: "btn btn-lg btn-primary" %>
            <% end %>
          <% end %>
        </aside>
      <% end %>
         
        
      <h2>
        <% if @user.tipo == "M" %>
        <br />
          Especilização: <%= @user.especializacao %> <br />
          <% if @user.activated == false %>
            Essa conta ainda não foi ativada. O processo pode levar algum tempo. <br />
            <% if current_user.tipo == "A" %>
              <br /> <%= link_to 'Aprovar Conta', active_user_path(@user) %> <br />
            <% end %>
          <% end %>
        <% end %>
        <% if @user.tipo == "A" %>
          <b>Administrador do site</b> <br />
        <% end %>
      Endereço: <%= @user.endereco %> <%= link_to 'Mapa', "http://maps.google.com/?q="+@user.endereco,  :target => '_blank' %>  <br />
      Telefone: <%= @user.telefone %> <br />
        
      <% if @user == current_user && @user.tipo == "A" %>
        <br />
        Lista de usuários ainda não aprovados:
        <% @users.each do |user|%>
          <% if user.tipo == "M" && user.activated == false %>
            <li><%= link_to user.nome, user_path(user.id) %></li>
          <% end %>
        <% end %>
      <% end %>
      </h2>
</div>