config/routes.rb
Rails.application.routes.draw do
  resources :users do
   member do
      get 'activate'
     put 'activate'
   end
  end

  resources :sintomadoencas, shallow: true do
    resources :doencas
  end

get "users/:id/activate" => "users#activate", :as => "active_user"
  
  get 'doencas/new'

  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get 'signup'  => 'users#new'
  get 'm_signup'=> 'users#new_m'
  get 'edit'    => 'users#edit'
  #post 'users/ativar_medico'
  
  
  
  get 'add'     => 'doencas#new'
  get 'index_d' => 'doencas#index'
  get 'edit'    => 'doencas#edit'
  
  get 'add_sintoma' => 'sintomas#new'
  get 's_index' => 'sintomas#index'
  #get 'busca' => 'sintomas#search'
  get 'edit' => 'sintomas#edit'
  
  resources :account_activations, only: [:edit]

  resources :users
  
  resources :doencas 
  resources :sintomas
  resources :sintomadoencas
  
  get 'sd' => 'sintomadoencas#new' 
  get 'search' => 'sintomadoencas#search'
  get 'remove' => 'sintomadoencas#delete'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/doenca.rb
class Doenca < ActiveRecord::Base
    has_many :sintomadoencas#, dependent: :destroy, inverse_of: :ilness
    has_many :sintomas, through: :sintomadoencas

    scope :with_sintomas, ->(sintomas) { joins(sintomadoencas: :sintoma).where("sintomas.id in (?)", sintomas).group("doencas.id")
                                        .having("count(doencas.id) >= ?", (sintomas.present? ? sintomas.length : 0) ) }
    
    validates :nome, uniqueness: true,  presence: true, length: { maximum: 50 }
    validates :descricao, presence:true, length: {minimum: 150} 
    
    def self.for_sintomas(*s)
        Doenca.scoped.join(:sintomas).merge(Sintoma.sintoma(s))
    end
  
end

app/controllers/doencas_controller.rb
class DoencasController < ApplicationController
 before_action :logged_in_user, only: [:new, :create]
 before_action :user_type, only: [:new, :create, :update, :edit]
 
 
  @sintoma=Sintoma.new
  @sintomadoencas = Sintomadoenca.new
  
  def show
    @doenca = Doenca.find_by_id(params[:id])
    @sintomadoencas = Sintomadoenca.find_by_doenca_id(params[:id])
    @users = User.all
  end

  def index
    @doenca = Doenca.paginate(page: params[:page])
  end

  def new
    @doenca = Doenca.new
  end
  
  def create
    @doenca = Doenca.new(doenca_params)
    if @doenca.save
      flash[:success] = "Adicionado com sucesso"
      redirect_to @doenca
    else
      render 'new'
    end
  end
  
  #####
  def update
    @doenca = Doenca.find(params[:id])
    @sintomadoenca = Sintomadoenca.find(params[:id])
    if @doenca.update_attributes(doenca_params)
     flash[:success] = "Atualizado."
     redirect_to @doenca
    else
      render 'edit'
    end
  end
  
  def edit
    @doenca = Doenca.find(params[:id])
  end
  #####
  
  private

    def doenca_params
      params.require(:doenca).permit(:nome, :descricao, :especializacao)
      #, :sintoma
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Você precisa estar conectado."
        redirect_to login_url
      end
    end
    
    def user_type
      #@user = User.find(params[:id])
      unless current_user.tipo == "M" || current_user.tipo == "A"
        flash[:danger] = "Você não possui autorização para realizar essa ação."
        redirect_to index_d_url
      end
    end

end

app/helpers/doencas_helper.rb
module DoencasHelper
end

app/views/doencas/edit.html.erb
<% provide(:title, 'Alterar Informações') %>
<h1>Edite seu perfil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@doenca) do |f| %>
      <%= render 'shared/doenca_error_messages' %>

      <%= f.label :nome %>
      <%= f.text_field :nome, class: 'form-control' %>

      <%= f.label :descricao, "Descrição (mínimo 150 caracteres)" %>
      <%= f.text_area :descricao, class: 'form-control'  %>
      
      <%= f.submit "Salvar alterações", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/doencas/index.html.erb
<% provide(:title, 'Todas as doenças') %>
<h1>Todas as doenças: </h1>

<%= will_paginate @doenca%>

<ul class="doenca">
  <% @doenca.each do |doenca| %>
    <li>
      <%= link_to doenca.nome, doenca %>: 
      <%= truncate(doenca.descricao, :length => 100, :separator => ' ', :omission => '... (Mais)') %>
      <br />      <br />
    </li>
  <% end %>
</ul>

<%= will_paginate @doenca %>

app/views/doencas/new.html.erb
<% provide(:title, 'Registrar doença') %>
<h1>Registro de Doenças</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for(@doenca) do |f| %>
     <%= render 'shared/doenca_error_messages' %>
     
      <%= f.label :nome %>
      <%= f.text_field :nome, class: 'form-control' %>

      <%= f.label :especializacao, "Especialização" %>
      <%= f.text_field :especializacao, class: 'form-control' %>    

      <%= f.label :descricao, "Descrição (mínimo 150 caracteres)" %>
      <%= f.text_area :descricao, class: 'form-control'  %>

      <%= f.submit "Adicionar doença", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/doencas/show.html.erb
<% provide(:title, @doenca.nome) %>
  <section class="user_info">
      <h1>
        <%= @doenca.nome %>
      </h1>
      <aside class="col-md-4">
        <h2>
          Sintomas<br /> <br />
          <% @doenca.sintomas.each do |sintoma|%>
          <li><%= link_to sintoma.nome, sintoma_path(sintoma.id) %></li>
          <% end %>
      
          <% if @doenca.sintomas.present? == false %> 
            Nenhum sintoma registrado. <br />
          <% end %>
          <br />
      
          <%= link_to "Editar", edit_doenca_path, class: "btn btn-lg btn-primary"%><br />
          <br /><%= link_to "Adicionar sintomas",sd_path(:sintomadoenca => { :doenca_id => @doenca.id } ) %>
          <br /><%= link_to "Remover sintomas",remove_path(:sintomadoenca => { :doenca_id => @doenca.id } ) %>
        </h2>
      </aside>
      Área: <%= @doenca.especializacao %> <br />
        <% @users.each do |user|%>
          <% if user.tipo == "M" && user.activated == true && user.especializacao == @doenca.especializacao %>
            <li>Dr(a).<%= link_to user.nome, user_path(user.id) %></li>
          <% end %>
        <% end %>
        <br />
      <%= @doenca.descricao %>
    </section>
  