config/routes.rb
Rails.application.routes.draw do
  resources :users do
   member do
      get 'activate'
     put 'activate'
   end
  end

  resources :sintomadoencas, shallow: true do
    resources :doencas
  end

get "users/:id/activate" => "users#activate", :as => "active_user"
  
  get 'doencas/new'

  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get 'signup'  => 'users#new'
  get 'm_signup'=> 'users#new_m'
  get 'edit'    => 'users#edit'
  #post 'users/ativar_medico'
  
  
  
  get 'add'     => 'doencas#new'
  get 'index_d' => 'doencas#index'
  get 'edit'    => 'doencas#edit'
  
  get 'add_sintoma' => 'sintomas#new'
  get 's_index' => 'sintomas#index'
  #get 'busca' => 'sintomas#search'
  get 'edit' => 'sintomas#edit'
  
  resources :account_activations, only: [:edit]

  resources :users
  
  resources :doencas 
  resources :sintomas
  resources :sintomadoencas
  
  get 'sd' => 'sintomadoencas#new' 
  get 'search' => 'sintomadoencas#search'
  get 'remove' => 'sintomadoencas#delete'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Panacea - Trabalho de Conclusão de Curso 2015 IF-Sul Campus Sapucaia do Sul
  </small>
  <nav>
    <ul>
      <li><%= link_to "Sobre",   about_path %></li>
      <li><%= link_to "Contato", contact_path %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Panacea", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Principal", root_path %></li>
        <li><%= link_to "Ajuda", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Busca", s_index_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Minha Conta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sair", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'jquery.min', 'jquery-ui-1.8.2.custom.min.js' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>